language: go

go:
  - 1.10.x

before_install:
  - go get -t -v golang.org/x/tools/cmd/goimports
  - go get -t -v . ./cli/.

script:
  - make test
  - make all

after_success:
  - bash <(curl -s https://codecov.io/bash)
