language: go

go:
  - 1.10.x

before_install:
  - go get -t -v . ./iicp/.

script:
  - cd iicp && go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - cd iicp && bash <(curl -s https://codecov.io/bash)
