package icp

const (
	ERR_OK                 = "ERR_OK"
	ERR_NO_CERT_PATH       = "ERR_NO_CERT_PATH"
	ERR_ISSUER_NOT_FOUND   = "ERR_ISSUER_NOT_FOUND"
	ERR_LOCKED_MULTI_ERROR = "ERR_LOCKED_MULTI_ERROR"
	ERR_MAX_DEPTH_REACHED  = "ERR_MAX_DEPTH_REACHED"
	ERR_PARSE_CERT         = "ERR_PARSE_CERT"
	ERR_PARSE_RSA_PUBKEY   = "ERR_PARSE_RSA_PUBKEY"
	ERR_READ_CERT_FILE     = "ERR_READ_CERT_FILE"
	ERR_NOT_BEFORE_DATE    = "ERR_NOT_BEFORE_DATE"
	ERR_NOT_AFTER_DATE     = "ERR_NOT_AFTER_DATE"
	ERR_BAD_SIGNATURE      = "ERR_BAD_SIGNATURE"
	ERR_NOT_IMPLEMENTED    = "ERR_NOT_IMPLEMENTED"
	ERR_UNKOWN_ALGORITHM   = "ERR_UNKOWN_ALGORITHM"
)
