package icp

const (
	ERR_OK                        = "ERR_OK"
	ERR_FAILED_TO_BUILD_CERT_PATH = "ERR_FAILED_TO_BUILD_CERT_PATH"
	ERR_ISSUER_NOT_FOUND          = "ERR_ISSUER_NOT_FOUND"
	ERR_LOCKED_MULTI_ERROR        = "ERR_LOCKED_MULTI_ERROR"
	ERR_MAX_DEPTH_REACHED         = "ERR_MAX_DEPTH_REACHED"
	ERR_PARSE_CERT                = "ERR_PARSE_CERT"
	ERR_READ_CERT_FILE            = "ERR_READ_CERT_FILE"
)
