=pod

=head1 NAME

icp_errc_code - Returns the int error code from L<icp_errc(3)>

=head1 SYNOPSIS

  #include "libICP.h"

  int icp_errc_code(icp_errc errc);

=head1 EXAMPLE

  #include "libICP.h"
  
  printf("%d\n", icp_errc_code(some_errc));

=head1 SEE ALSO

L<libICP(3)> - General library documentation

L<icp_errc(3)>

=cut