=pod

=head1 NAME

icp_cert_issuer - Gets the certificate issuer as string

=head1 SYNOPSIS

  #include "libICP.h"
  
  char* icp_cert_issuer(icp_cert cert);

=head1 SEE ALSO

L<libICP(3)> - General library documentation

L<icp_cert(3)>

L<icp_cert_subject(3)>, L<icp_cert_subject_map(3)>, L<icp_cert_issuer(3)>, L<icp_cert_issuer_map(3)>

=cut