=pod

=head1 NAME

libICP - An ICP-Brasil CAdES library (part of the OpenICP-BR project)

=head1 SYNOPSIS

libICP is a golang library for processing ICP-Brasil CAdES digital signatures.

These man pages document the C wrapper for the original library.

=head1 COMPILATION

To compile a program that uses this library, simply run:

  gcc my_program.c -o my_program /path/to/installation/libICP.a -I/path/to/installation

On macOS:

  gcc my_program.c -o my_program -lICP -framework CoreFoundation -framework Security

=head1 SEE ALSO

L<icp_version(3)>

L<icp_errc(3)> - Error

L<icp_errc(3)> - Coded error

L<icp_cert(3)> - Certificate

L<icp_store(3)> - CA Store

L<icp_pfx(3)> - PFX/p12 file (certificate with encrypted key) 

=cut